import Head from 'next/head'
import { Inter } from '@next/font/google'
import Cover from '@/components/secCover'
import Prices from '@/components/secPrices'
import Calc from '@/components/secCalc'
import Types from '@/components/secTypes'
import About from '@/components/secAbout'
import Why from '@/components/secWhy'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Cover/>
      <Prices/>
      <Calc/>
      <Types/>
      <Why/>
      <About/>
      </main>
    </>
  )
}
