import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navigation from '@/components/secCover'
import Prices from '@/components/secPrices'
import Calc from '@/components/secCalc'
import Types from '@/components/secTypes'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Navigation/>
      <Prices/>
      <Calc/>
      <Types/>
      </main>
    </>
  )
}
